### ISSUE TITLE
getElemByIdSafe throwing exception when loading image

### ISSUE THREAD

**Issue by Habel91** [devforth/painterro#134]
I create a Painterro object and hide the open button from the toolbar. Then I load an image using a base64 string 

`let p = Painterro({
        ...
        hiddenTools: {
             ...,
             'open'
        },
         ...});

p.show('data:image/jpeg;base64,/9j/4AAQSkZJRgAB...');`

But that image is never shown in painterro. Instead an exception ("Can't get element with id=undefined, please create an issue here, we will easily fx it:") is thrown in the getElemByIdSafe function when trying to get the open button HTMLElement (since this element is hidden).

The existence of this HTMLElement would be checked anyway in the startLoading() function after the call to getElemByIdSafe() but because this exception is thrown it will never be checked an the image is never shown.

**Comment by ivictbor** [comment]
@Habel91 thanks a lot, working on fix

**Comment by ivictbor** [comment]
@Habel91 fixed in latest release. please 

```
npm i painterro@latest --save
```

The thing is we faced a lot of cases when Painterro was touching users projects DOM when we did such selectors,

e.g. :

```
const buttonId =  undefined
getElementById(buttonId).disabled = True
```

and the user had some button in his forms, outside of painterro defined is `<button class='x'>Press</button>` - formally has no id, so it was disabled.

So we decided to wrap it in function which would call exception so users would report it just in case 😜

I suspect almost all cases are covered but you've found one, thanks for that, don't hesitate to create any issues 😉

**Comment by Habel91** [comment]
@ivictbor Thanks a lot for your quick response and the quick fix! 

I see why you made these changes and fortunately the issue was easy to find 🙂
