### ISSUE TITLE
Angular app - "Painterro is not a function" after deployment

### ISSUE THREAD

**Issue by Foreys** [devforth/painterro#153]
Hi,

**Describe the bug**
Painterro is not working after deployment on the server

**Painterro version**
v1.2.61

I recently tried adding painterro to an Angular-based project. Everything locally works fine until the project is published. After publishing I get an error:

![image](https://user-images.githubusercontent.com/57001467/131362971-6a9a709c-18ed-4b97-a304-dcefc3039c8e.png)

To import, I use in my component:

import * as Painterro from '../../../node_modules/painterro/build/painterro.min.js'

my package.json:

![image](https://user-images.githubusercontent.com/57001467/131363158-b41e5312-9bb9-43bd-a32e-5c775c687786.png)

I also tried to like download the painterro and import it from the project assets but I get the same result (after publish of course).

What was tried:
-Using lower version of painterro (1.2.10)
-Try to: Import Painterro from 'painterro' - but that gives me an error 404.

I spend like whole day searching for fix, but I couldn't find it. 

If I need to provide any more information, please ask.

Best Regards,
Maciej

**Comment by ivictbor** [comment]
Why you import from min file? This file s intended for browsers.
You should just

```
import Painterro from 'painterro';
```

as sated in Readme. But please explain who advised you this one `from '../../../node_modules/painterro/build/painterro.min.js`

**Comment by Foreys** [comment]
It was my idea cause

`Import Painterro from 'painterro' `
or either 
`Import { Painterro } from 'painterro' `

is causing:

![image](https://user-images.githubusercontent.com/57001467/131365769-d44f923f-7dff-46fc-9cc0-1efe4e716386.png)

I even tried to install it on app with newest angular/typescript

From Visual Studio code I'm getting:

![image](https://user-images.githubusercontent.com/57001467/131366427-0b899ca2-a13d-4ec1-89fa-c66343c5dcae.png)

**Comment by ivictbor** [comment]
Why you are using brackets?

Once again, please check Readme

![Uploading Screenshot_20210830-191652_Chrome.jpg…]()

**Comment by ivictbor** [comment]
Could you please provide minimal project source on Angular (minimal example created from scratch)

**Comment by ivictbor** [comment]
@Foreys advice which can change your developer's career: if something is not working, first of all, try to create a minimal project. For me it took a couple of minutes to do it on Angular and it is with creating hints in parallel so you can check it:
https://hinty.io/devforth/add-painterro-into-angular-app/ (Though I mostly don't use Angular and it does not inspire me). If the minimal demo is not working - then issue in library so you can go to creator and he will be able to troubleshoot it easily. Otherwise, you should apply changes incrementally reducing diff with your other project. All professionals doing things in this way. Just spy on how users contribute on GitHub with issues

**Comment by ivictbor** [comment]
Closing, as not painterro related. Please follow the steps from the post to integrate Painterro into Angular app.
