### ISSUE TITLE
On screen .resize() & .hide(), the Painterro canvas gets cleared.

### ISSUE THREAD

**Issue by ravishankardubey** [devforth/painterro#155]
**Describe the bug**
There are two scenarios in which the Painterro canvas is getting cleared
1. When the screen is resized ( .resize() ), the canvas gets cleared automatically.
2. After hiding the Painterro, the canvas gets cleared on the next show()

**Painterro version**
v1.2.65

**Comment by ivictbor** [comment]
Hi @ravishankardubey 

1. Internal method in main.js resize is not documented and intended only for internal use, so it was not created to preserve canvas, you can see full code of resize in canvas.js in handler `this.scaleButton.onclick = () => {` . If you need resize API to be called from externall world it should be implemented and documented first. I added `doScale` API for you. 
2. This is expected behaviour when you pass undefined because most users will want to clean up area. Pass `false` explicitly to load previous state as mentioned in readme

![image](https://user-images.githubusercontent.com/1838656/167091066-63150b49-f60e-44da-b40a-46ed7444da22.png)
