### ISSUE TITLE
[Bug] Issue when uploading image in IE/Edge

### ISSUE THREAD

**Issue by AnnaGj** [devforth/painterro#38]
There is a bug on IE and Edge when trying upload an image. After selecting the image from the explorer it won't display into the canvas. The upload only works if you try it several times.
I have seen this issue on both v.0.2.67 and  v.0.2.68. 
This also happens when using the paste command, though it works ok when you drag and drop an image into the canvas.
Thank you.

**Comment by ivictbor** [comment]
Hi @AnnaGj! Thanks a lot for bug report!

**Comment by ivictbor** [comment]
@AnnaGj could you please try to reproduce on 1.2.29+ e.g. here: https://hinty.io/devforth/multiple-painterro-instances-on-one-page/

**Comment by ivictbor** [comment]
@AnnaGj made a fix, working for me, IE version is specified

![image](https://user-images.githubusercontent.com/1838656/116261635-83927c80-a780-11eb-90af-e83bcd97133d.png)


> This also happens when using the paste command, 

If you mean something like Ctrl + V it will never work in IE because it has no `document.onpaste` event.

Also please remember that internet explorer is not supported by Painterro and it is even not supported by Microsoft,
no one supports it, it is kinda can't be considered as a browser at all. 

Painterro works well in Edge which is supported by us and Microsoft.

Though of course, we are trying to fix all user's requests like yours. Also in any references to IE issue please specify why you have IE users at all and why can't ask them to use supported browsers.
