### ISSUE TITLE
[Bug] Insert text on IE

### ISSUE THREAD

**Issue by Maleantes** [devforth/painterro#44]
Hi !

The text insertion doesn't work under IE. Do you plan a fix or is there a way to workaround ?

Thanks by advance

**Comment by ivictbor** [comment]
@Maleantes Which version did you try? And which do you need it to be available?

**Comment by Sony-GG** [comment]
Hi
 Text insertion on Google chrome is not working. Any way to solve it.
Thanks

**Comment by ivictbor** [comment]
@Maleantes 
Hi, after @alexnavratil I updated polifils required to updated version of babel and tested on IE, for me it looks working, tested basic features including text

![image](https://user-images.githubusercontent.com/1838656/116143939-68722f00-a6e4-11eb-87a6-483ce16c7728.png)

(Of course without features like clipboard image pasting which is not available in IE by its nature, and somewhy without hotkeys, but such support in IE would cost a lot of time, so I am not going to working on it without explaining valuable reason - e.g. you have a million guys which somehow can't download chrome because or law restrictions and will need a Painterro copy-paste feature)

Closing now, feel free to reopen to continue any discussion related to IE
