### ISSUE TITLE
l want add icon to ptro-bar(tool)

### ISSUE THREAD

**Issue by Vin201487** [devforth/painterro#75]
how to clear existing edits

**Comment by Vin201487** [comment]
@ivictbor

**Comment by ivictbor** [comment]
Hi @Vin201487. You could use undoState  https://github.com/devforth/painterro/blob/master/js/worklog.js#L94
And repeated it while `this.current.prev !== null`

**Comment by Vin201487** [comment]
let me see

**Comment by ivictbor** [comment]
@Vin201487 did it work?

**Comment by Vin201487** [comment]
@ivictbor no!  Can you describe it in detail , thanks

**Comment by Vin201487** [comment]
by the way can l change the exsting  icon style ,for example ,let brush become pencil @ivictbor

**Comment by ivictbor** [comment]
> @ivictbor no! Can you describe it in detail , thanks

Please post code you tried

> by the way can l change the existing icon style
yes sure, but by patching library itself.

**Comment by Vin201487** [comment]
need i change your source code? or  in my own file  rewrite it

**Comment by ivictbor** [comment]
> need i change your source code? or in my own file rewrite it

To add a new button with new icon? Which button exactly? Do you mean button "to clear existing edits" as you wrote? 
If yes, currently Painterro has no such button - you have "Eraser" tool to clear content and "Undo" tool to undone changes.
If you need to another button, yes you have to change source code. To achieve it:
1. you need to search for tools array and add new item to that array
2. Create a new SVG icon and add it to icon font, using this section https://github.com/devforth/painterro#regenerating-icons-font (in painterro we compile SVG files into font)
3. define handler for your tool which could e.g. undoState while it will not be cleared or will just clear directly, there is a code already, because same button exist in dialog, not on panel:
![image](https://user-images.githubusercontent.com/1838656/69615183-28190800-103d-11ea-9ea0-d5334e9c8c0b.png)

**Comment by Vin201487** [comment]
fine, l must change source code , it seems
thanks,i worry about  whether i overlook some function , now l will change this source code
